version: "3.9"
services:
  auth:
    build:
      context: .
      dockerfile: ./docker/auth/Dockerfile
    ports:
      - "8081:8080"
    environment:
      MONGO_CONNECTION_STRING: mongodb://user:password@mongodb:27017/
      MONGO_DATABASE: lpaas
      JWT_SECRET: keyboard cat
      PORT: 8080

  lpaas:
    build:
      context: .
      dockerfile: ./docker/lpaas/Dockerfile
    ports:
      - "8080:8080"
    environment:
      LPAAS_JWT_SECRET: keyboard cat
      LPAAS_MONGO_CONNECTION_STRING: mongodb://user:password@mongodb:27017/
      LPAAS_MONGO_DATABASE: lpaas

  mongodb:
    build: ./docker/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
