version: "3.9"
services:
  auth:
    build:
      context: .
      dockerfile: ./docker/auth/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./generated-keys/private.pkcs8.pem:/etc/ssl/certs/my_key.pem
    environment:
      AUTH_MONGO_CONNECTION_STRING: mongodb://user:password@mongodb:27017/
      AUTH_MONGO_DATABASE: lpaas
      AUTH_PRIVATE_KEY_PATH: /etc/ssl/certs/my_key.pem
      AUTH_PORT: 8080

  lpaas:
    build:
      context: .
      dockerfile: ./docker/lpaas/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./generated-keys/public.pem:/etc/ssl/certs/auth_key.pem
    environment:
      LPAAS_MONGO_CONNECTION_STRING: mongodb://user:password@mongodb:27017/
      LPAAS_MONGO_APPLICATION_DATABASE: lpaas
      LPAAS_PUBLIC_KEY_PATH: /etc/ssl/certs/auth_key.pem
      LPAAS_PORT: 8080

  mongodb:
    build: ./docker/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
