version: "3.9"
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8081:8080"
    env_file:
      - .lpaas.env

  lpaas:
    build:
      context: .
      dockerfile: Dockerfile.lpaas
    ports:
      - "8080:8080"
    env_file:
      - .lpaas.env

  mongodb:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
