rootProject.name = "lpaas"
include("utils")
include("domain")
include("serialization")
include("core")
include("authorization")
include("delivery-vertx")
include("serialization-vertx")
include("authentication-vertx")
include("persistence-inmemory")
include("persistence-mongo")
include("test-lib-vertx")
include("test-fixtures-domain")
include("persistence-mongo")
include("main-vertx-inmemory")
include("main-vertx-mongo")

include("client")
