rootProject.name = "lpaas"
include("utils")
include("domain")
include("serialization")
include("core")
include("auth")
include("delivery-vertx")
include("persistence-inmemory")
include("persistence-mongo")
include("test-lib-vertx")
include("main-vertx-inmemory")
include("persistence-mongo")
